name: test
on: [workflow_dispatch]
jobs:
  run-linux-commands:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        uses: actions/checkout@v4
      - name: test2
        run: ${{ secrets.TEST1 }}
      - name: test3
        run: ${{ secrets.TEST2 }}
